# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vivir en España - Estos Panas
email: carlos@camconsulting.online
description: Una mano amiga que te recibe para ayudarte en tu nueva vida en España
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.estospanas.com" # the base hostname & protocol for your site
twitter_username: estospanasweb
twitter:
  site: estospanasweb
  content: summary_large_image

facebook:
  publisher: https://www.facebook.com/estospanas/
google_site_verification:


# Build settings
markdown: kramdown

gems:
  - jekyll-seo-tag

fb_admins:          https://www.facebook.com/carlosaugustomarchena
fb_appid:           1138698906223730
avatar:             /images/avatarCA.png
